/**
 * Единый каталог кодов ошибок платформы DoruTJ.
 *
 * Источники (единственные, транскрипция без додумывания, DTJ-005):
 * - `docs/spec/12-api-conventions-auth-tenancy.md` §2.1 — транспортные/auth/tenancy коды;
 * - `docs/spec/10-domain-model.md` §«Доменные ошибки» — доменные коды и их HTTP-статусы.
 *
 * ОДИН enum на весь каталог (не два пересекающихся адресных пространства строк, см. риски
 * тикета DTJ-005): код, переиспользуемый обоими источниками (например `VALIDATION_ERROR`,
 * `CONFLICT`, `NOT_FOUND`, `BUSINESS_RULE_VIOLATION`, `CONSENT_REQUIRED`,
 * `INVALID_WEBHOOK_SIGNATURE`, `OTP_LOCKED`), объявлен здесь один раз.
 *
 * `ERROR_HTTP_STATUS` — HTTP-статус хранится РЯДОМ с каталогом (не в `domain-errors.ts`), т.к.
 * им пользуется и `TransportExceptionFilter`, и `DomainExceptionFilter` (оба — DTJ-018).
 * `Record<ErrorCode, number>` заставляет TS требовать статус для КАЖДОГО члена enum — это и есть
 * "тест-сверка" критерия приёмки №1, проверяемая компилятором, а не только unit-тестом.
 */

export enum ErrorCode {
  // ---- Транспорт/валидация (400) — `12-api-conventions-auth-tenancy.md` §2.1 ----
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  IDEMPOTENCY_KEY_REQUIRED = 'IDEMPOTENCY_KEY_REQUIRED',
  INVALID_CURSOR = 'INVALID_CURSOR',
  TENANT_NOT_RESOLVED = 'TENANT_NOT_RESOLVED',
  CONSENT_REQUIRED = 'CONSENT_REQUIRED',

  // ---- Аутентификация (401) ----
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_INVALID = 'TOKEN_INVALID',
  REFRESH_TOKEN_INVALID = 'REFRESH_TOKEN_INVALID',
  REFRESH_TOKEN_REUSE_DETECTED = 'REFRESH_TOKEN_REUSE_DETECTED',
  INVALID_TELEGRAM_INIT_DATA = 'INVALID_TELEGRAM_INIT_DATA',
  TELEGRAM_AUTH_DATE_EXPIRED = 'TELEGRAM_AUTH_DATE_EXPIRED',
  PHARMACY_API_KEY_INVALID = 'PHARMACY_API_KEY_INVALID',
  PHARMACY_SIGNATURE_INVALID = 'PHARMACY_SIGNATURE_INVALID',
  PHARMACY_TIMESTAMP_OUT_OF_WINDOW = 'PHARMACY_TIMESTAMP_OUT_OF_WINDOW',
  PHARMACY_REQUEST_REPLAYED = 'PHARMACY_REQUEST_REPLAYED',
  MTLS_REQUIRED = 'MTLS_REQUIRED',
  INVALID_WEBHOOK_SIGNATURE = 'INVALID_WEBHOOK_SIGNATURE',

  // ---- Авторизация/tenancy (403) ----
  FORBIDDEN = 'FORBIDDEN',
  INSUFFICIENT_ROLE = 'INSUFFICIENT_ROLE',
  TENANT_SUSPENDED = 'TENANT_SUSPENDED',
  CROSS_TENANT_ACCESS_DENIED = 'CROSS_TENANT_ACCESS_DENIED',
  WS_ROOM_FORBIDDEN = 'WS_ROOM_FORBIDDEN',

  // ---- Не найдено (404) ----
  NOT_FOUND = 'NOT_FOUND',
  UNKNOWN_TENANT_SLUG = 'UNKNOWN_TENANT_SLUG',
  UNSUPPORTED_LOCALE = 'UNSUPPORTED_LOCALE',

  // ---- Транспорт (408/409/413/415) ----
  REQUEST_TIMEOUT = 'REQUEST_TIMEOUT',
  CONFLICT = 'CONFLICT',
  IDEMPOTENCY_KEY_CONFLICT = 'IDEMPOTENCY_KEY_CONFLICT',
  PAYLOAD_TOO_LARGE = 'PAYLOAD_TOO_LARGE',
  UNSUPPORTED_MEDIA_TYPE = 'UNSUPPORTED_MEDIA_TYPE',

  // ---- Бизнес-правила / rate limit (422/423/429) ----
  BUSINESS_RULE_VIOLATION = 'BUSINESS_RULE_VIOLATION',
  OTP_LOCKED = 'OTP_LOCKED',
  OTP_REQUEST_RATE_LIMITED = 'OTP_REQUEST_RATE_LIMITED',
  RATE_LIMITED = 'RATE_LIMITED',

  // ---- Сервер (500/502/503) ----
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  BAD_GATEWAY = 'BAD_GATEWAY',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',

  // ---- Доменные: ValidationError — `10-domain-model.md` §«Доменные ошибки» (400) ----
  INVALID_PHONE_FORMAT = 'INVALID_PHONE_FORMAT',
  INVALID_COORDINATES = 'INVALID_COORDINATES',
  ORDER_TOTAL_MISMATCH = 'ORDER_TOTAL_MISMATCH',
  INVALID_RESTOCK_QUANTITY = 'INVALID_RESTOCK_QUANTITY',
  INVALID_PRICE = 'INVALID_PRICE',
  MISSING_RESOLUTION_REASON = 'MISSING_RESOLUTION_REASON',
  AMBIGUOUS_DATE_FORMAT = 'AMBIGUOUS_DATE_FORMAT',

  // ---- Доменные: ConflictError (409) ----
  TENANT_SLUG_TAKEN = 'TENANT_SLUG_TAKEN',
  DOMAIN_TAKEN = 'DOMAIN_TAKEN',
  RETURN_ALREADY_ACTIVE = 'RETURN_ALREADY_ACTIVE',
  DISPUTE_ALREADY_ACTIVE = 'DISPUTE_ALREADY_ACTIVE',
  LEDGER_IMBALANCE = 'LEDGER_IMBALANCE',

  // ---- Доменные: ForbiddenTransitionError (409) ----
  INVALID_STATE_TRANSITION = 'INVALID_STATE_TRANSITION',

  // ---- Доменные: BusinessRuleViolationError и потомки (422, кроме отмеченных) ----
  PRESCRIPTION_NOT_VERIFIED = 'PRESCRIPTION_NOT_VERIFIED',
  CONTROLLED_SUBSTANCE_FORBIDDEN = 'CONTROLLED_SUBSTANCE_FORBIDDEN',
  EXPIRED_STOCK = 'EXPIRED_STOCK',
  COD_FORBIDDEN_FOR_RX = 'COD_FORBIDDEN_FOR_RX',
  COD_LIMIT_EXCEEDED = 'COD_LIMIT_EXCEEDED',
  INSUFFICIENT_STOCK = 'INSUFFICIENT_STOCK',
  RESTOCK_CONDITIONS_NOT_MET = 'RESTOCK_CONDITIONS_NOT_MET',
  CONTROLLED_SUBSTANCE_MUST_BE_DESTROYED = 'CONTROLLED_SUBSTANCE_MUST_BE_DESTROYED',
  PARENT_CHAIN_NOT_ACTIVE = 'PARENT_CHAIN_NOT_ACTIVE',
  PHARMACY_SUSPENDED = 'PHARMACY_SUSPENDED', // 403
  CASH_AMOUNT_MISMATCH = 'CASH_AMOUNT_MISMATCH',
  COURIER_TENANT_MISMATCH = 'COURIER_TENANT_MISMATCH', // 403
  COURIER_NOT_ELIGIBLE = 'COURIER_NOT_ELIGIBLE',
  SELF_DEALING_FORBIDDEN = 'SELF_DEALING_FORBIDDEN', // 403
  TENANT_CONFIRMATION_PENDING = 'TENANT_CONFIRMATION_PENDING', // 409
  PAYOUT_ON_HOLD = 'PAYOUT_ON_HOLD', // 409
  CHAIN_APPLICATION_ALREADY_EXISTS = 'CHAIN_APPLICATION_ALREADY_EXISTS', // 409 [SRS-ADM-007, EP-03]
  ALREADY_REVIEWED = 'ALREADY_REVIEWED', // 409 [SRS-ADM-080, EP-03]

  // ---- Доменные: SecurityError и потомки (401/403) ----
  UNAUTHORIZED_ADJUSTMENT = 'UNAUTHORIZED_ADJUSTMENT', // 403
  PHARMACY_NOT_IN_CHAIN_SCOPE = 'PHARMACY_NOT_IN_CHAIN_SCOPE', // 403 [SRS-ADM-046, EP-05 DTJ-142/156]

  // ---- Доменные: OtpError и потомки (400/423) ----
  OTP_EXPIRED = 'OTP_EXPIRED',
  OTP_MISMATCH = 'OTP_MISMATCH',

  // ---- Доменные: ExternalIntegrationError и потомки (503) ----
  PAYMENT_PROVIDER_UNAVAILABLE = 'PAYMENT_PROVIDER_UNAVAILABLE',
  OCR_PROVIDER_UNAVAILABLE = 'OCR_PROVIDER_UNAVAILABLE',
  SMS_PROVIDER_UNAVAILABLE = 'SMS_PROVIDER_UNAVAILABLE',
}

/** HTTP-статус для каждого `ErrorCode` (`TransportExceptionFilter`/`DomainExceptionFilter`, DTJ-018). */
export const ERROR_HTTP_STATUS: Record<ErrorCode, number> = {
  [ErrorCode.VALIDATION_ERROR]: 400,
  [ErrorCode.IDEMPOTENCY_KEY_REQUIRED]: 400,
  [ErrorCode.INVALID_CURSOR]: 400,
  [ErrorCode.TENANT_NOT_RESOLVED]: 400,
  [ErrorCode.CONSENT_REQUIRED]: 400,

  [ErrorCode.UNAUTHENTICATED]: 401,
  [ErrorCode.TOKEN_EXPIRED]: 401,
  [ErrorCode.TOKEN_INVALID]: 401,
  [ErrorCode.REFRESH_TOKEN_INVALID]: 401,
  [ErrorCode.REFRESH_TOKEN_REUSE_DETECTED]: 401,
  [ErrorCode.INVALID_TELEGRAM_INIT_DATA]: 401,
  [ErrorCode.TELEGRAM_AUTH_DATE_EXPIRED]: 401,
  [ErrorCode.PHARMACY_API_KEY_INVALID]: 401,
  [ErrorCode.PHARMACY_SIGNATURE_INVALID]: 401,
  [ErrorCode.PHARMACY_TIMESTAMP_OUT_OF_WINDOW]: 401,
  [ErrorCode.PHARMACY_REQUEST_REPLAYED]: 401,
  [ErrorCode.MTLS_REQUIRED]: 401,
  [ErrorCode.INVALID_WEBHOOK_SIGNATURE]: 401,

  [ErrorCode.FORBIDDEN]: 403,
  [ErrorCode.INSUFFICIENT_ROLE]: 403,
  [ErrorCode.TENANT_SUSPENDED]: 403,
  [ErrorCode.CROSS_TENANT_ACCESS_DENIED]: 403,
  [ErrorCode.WS_ROOM_FORBIDDEN]: 403,

  [ErrorCode.NOT_FOUND]: 404,
  [ErrorCode.UNKNOWN_TENANT_SLUG]: 404,
  [ErrorCode.UNSUPPORTED_LOCALE]: 404,

  [ErrorCode.REQUEST_TIMEOUT]: 408,
  [ErrorCode.CONFLICT]: 409,
  [ErrorCode.IDEMPOTENCY_KEY_CONFLICT]: 409,
  [ErrorCode.PAYLOAD_TOO_LARGE]: 413,
  [ErrorCode.UNSUPPORTED_MEDIA_TYPE]: 415,

  [ErrorCode.BUSINESS_RULE_VIOLATION]: 422,
  [ErrorCode.OTP_LOCKED]: 423,
  [ErrorCode.OTP_REQUEST_RATE_LIMITED]: 429,
  [ErrorCode.RATE_LIMITED]: 429,

  [ErrorCode.INTERNAL_ERROR]: 500,
  [ErrorCode.BAD_GATEWAY]: 502,
  [ErrorCode.SERVICE_UNAVAILABLE]: 503,

  [ErrorCode.INVALID_PHONE_FORMAT]: 400,
  [ErrorCode.INVALID_COORDINATES]: 400,
  [ErrorCode.ORDER_TOTAL_MISMATCH]: 400,
  [ErrorCode.INVALID_RESTOCK_QUANTITY]: 400,
  [ErrorCode.INVALID_PRICE]: 400,
  [ErrorCode.MISSING_RESOLUTION_REASON]: 400,
  [ErrorCode.AMBIGUOUS_DATE_FORMAT]: 400,

  [ErrorCode.TENANT_SLUG_TAKEN]: 409,
  [ErrorCode.DOMAIN_TAKEN]: 409,
  [ErrorCode.RETURN_ALREADY_ACTIVE]: 409,
  [ErrorCode.DISPUTE_ALREADY_ACTIVE]: 409,
  [ErrorCode.LEDGER_IMBALANCE]: 409,

  [ErrorCode.INVALID_STATE_TRANSITION]: 409,

  [ErrorCode.PRESCRIPTION_NOT_VERIFIED]: 422,
  [ErrorCode.CONTROLLED_SUBSTANCE_FORBIDDEN]: 422,
  [ErrorCode.EXPIRED_STOCK]: 422,
  [ErrorCode.COD_FORBIDDEN_FOR_RX]: 422,
  [ErrorCode.COD_LIMIT_EXCEEDED]: 422,
  [ErrorCode.INSUFFICIENT_STOCK]: 422,
  [ErrorCode.RESTOCK_CONDITIONS_NOT_MET]: 422,
  [ErrorCode.CONTROLLED_SUBSTANCE_MUST_BE_DESTROYED]: 422,
  [ErrorCode.PARENT_CHAIN_NOT_ACTIVE]: 422,
  [ErrorCode.PHARMACY_SUSPENDED]: 403,
  [ErrorCode.CASH_AMOUNT_MISMATCH]: 422,
  [ErrorCode.COURIER_TENANT_MISMATCH]: 403,
  [ErrorCode.COURIER_NOT_ELIGIBLE]: 422,
  [ErrorCode.SELF_DEALING_FORBIDDEN]: 403,
  [ErrorCode.TENANT_CONFIRMATION_PENDING]: 409,
  [ErrorCode.PAYOUT_ON_HOLD]: 409,
  [ErrorCode.CHAIN_APPLICATION_ALREADY_EXISTS]: 409,
  [ErrorCode.ALREADY_REVIEWED]: 409,

  [ErrorCode.UNAUTHORIZED_ADJUSTMENT]: 403,
  [ErrorCode.PHARMACY_NOT_IN_CHAIN_SCOPE]: 403,

  [ErrorCode.OTP_EXPIRED]: 400,
  [ErrorCode.OTP_MISMATCH]: 400,

  [ErrorCode.PAYMENT_PROVIDER_UNAVAILABLE]: 503,
  [ErrorCode.OCR_PROVIDER_UNAVAILABLE]: 503,
  [ErrorCode.SMS_PROVIDER_UNAVAILABLE]: 503,
}
